### ISSUE TITLE
ScoreCard SAST

### ISSUE THREAD

**Issue by maennchen** [ash-project/ash#2092]
**Is your feature request related to a problem? Please describe.**

ScoreCard does not detect your Credo SAST usage since reporting to GitHub is not set up.

**Describe the solution you'd like**

Report Credo Output to GitHub.

**Describe alternatives you've considered**

none

**Express the feature either with a change to resource syntax, or with a change to the resource interface**

Example: https://github.com/erlef/oidcc/blob/6bfde287140b06c3ea3ffa3ed425f75eceeecf12/.github/workflows/part_test.yml#L405-L410

```yml
      - run: mix credo --format sarif > results.sarif
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@ff0a06e83cb2de871e5a09832bc6a81e7276941f # v3.28.18
        with:
          sarif_file: results.sarif
          category: credo
```

Also set the `security-events: write` permission to ensure that the SAST Reporting is allowed.

**Additional context**

The ScoreCard check will not immediately report a 10 since it scans recent commits to detect usage. The number will increase over the next few weeks.

Follow up to #2089
